### PR TITLE
add Equal func

### PR DESCRIPTION
**Pull request by ahfuzhang**

### CODE REVIEW

**Comment by josharian** [comment]
I believe that the runtime already contains this optimization. Have you checked?

**Comment by ahfuzhang** [comment]
runtime not compare pointer.
I add my test code here:

```go
package main

import (
	"fmt"
	"os"
	"reflect"
	"time"
	"unsafe"
)

// copy from prometheus source code

// NoAllocString convert []byte to string
func NoAllocString(buf []byte) string {
	return *(*string)(unsafe.Pointer(&buf))
}

// NoAllocBytes convert string to []byte
func NoAllocBytes(buf string) []byte {
	// not safe: return *(*[]byte)(unsafe.Pointer(&buf))
	x := (*reflect.StringHeader)(unsafe.Pointer(&buf))
	h := reflect.SliceHeader{Data: x.Data, Len: x.Len, Cap: x.Len}
	// nolint:all
	return *(*[]byte)(unsafe.Pointer(&h))
}

const maxSize = 1024 * 1024 * 32

func getData() []byte {
	content, _ := os.ReadFile("./main.go")
	buf := make([]byte, 0, maxSize)
	for cap(buf)-len(buf) > len(content) {
		buf = append(buf, content...)
	}
	return buf
}

const runTimes = 1000

func benchmark(s1 *string, s2 *string) {
	start := time.Now()
	for i := 0; i < runTimes; i++ {
		if *s1 != *s2 {
			panic("error")
		}
	}
	total := time.Since(start).Microseconds()
	fmt.Printf("avg: %.3f ns/op\n", float64(total)*1000.0/float64(runTimes))
}

const runTimes2 = 1000000

func benchmark2(s1 *string, s2 *string) {
	x := (*reflect.StringHeader)(unsafe.Pointer(s1))
	y := (*reflect.StringHeader)(unsafe.Pointer(s2))
	start := time.Now()
	for i := 0; i < runTimes2; i++ {
		if !((x.Len == y.Len && x.Data == y.Data) || *s1 == *s2) {
			panic("error")
		}
	}
	total := time.Since(start).Microseconds()
	fmt.Printf("avg: %.3f ns/op\n", float64(total)*1000.0/float64(runTimes2))
}


func main() {
	buf := getData()
	s := NoAllocString(buf)
	s1 := string(buf)
	benchmark2(&s, &s)  // avg: 0.905 ns/op
	benchmark(&s, &s)   // avg: 659591.000 ns/op
	benchmark(&s, &s1)  // avg: 1092023.000 ns/op
}

```

**Comment by josharian** [comment]
What GOARCH?

**Comment by josharian** [comment]
Thanks.Reported upstream as  https://github.com/golang/go/issues/64381

**Comment by josharian** [comment]
I appreciate the pull request. As the correct place to fix this is in the runtime, I am going to close this.

**Pull request closed without merging**
